### ISSUE TITLE
Rearrange MS/TP logic parameter setting dialog box to reduce click count

### ISSUE THREAD

**Issue by fakhrul-omar** [ADFTech/XTEC_X1_Public#11]
![image](https://user-images.githubusercontent.com/29793555/40598099-5142bb82-6278-11e8-91fc-c4ba1221552a.png)
-Include drop-down list directly in logic function parameter list dialog box and resize dialog box accordingly (possible with wxFlexGridSizer, just interface will become cluttered)

**Comment by fakhrul-omar** [comment]
Also removes PI and PID (deprecated? Syslab legacy?) and adds COV write and low-pass filters functions.

**Comment by kslee911** [comment]
Tested and closed.
