### ISSUE TITLE
Compile/Import/Export options in "Logic (IP)" tab are not working

### ISSUE THREAD

**Issue by fakhrul-omar** [ADFTech/XTEC_X1_Public#14]
While "Compile" menu item is definitely working (either tester forgot to ensure contiguous logic block(s) to be attached to start/end marker block or there's error in block(s) that is being compiled, "Import" and "Export" menu items are not working as all BACnet file related operation currently needs to be done via "BacFile" tab.

**Comment by kslee911** [comment]
Compile, import, export tested ok.
