### ISSUE TITLE
BACnet output object(s) on device doesn't match what is set in config-tool

### ISSUE THREAD

**Issue by fakhrul-omar** [ADFTech/XTEC_X1_Public#22]
Not sure where's the problem, either config-tool doesn't actually set the object on device or problem on device side.
- [x] Analog output object output/present value maintains at 4V
- [x] TO1 to TO10 LED doesn't light up when set

**Comment by fakhrul-omar** [comment]
MS/TP will missing some package during sending data, but after add retry function, it fine

**Comment by kslee911** [comment]
Tested ok
