### ISSUE TITLE
Analog/ Binary input not shown

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#32]
@fakhrul-omar

**Comment by fakhrul-omar** [comment]
Wonder if this is due to config-tool doesn't get reply when requesting object list when user starts connecting to DDC. If you try connecting it again, did the same thing happened?

**Comment by fakhrul-omar** [comment]
Refresh button to request for object list should be added then.

**Comment by wslow-adft** [comment]
@kslee911 @LOKJK  @thyong-adft  Ready for test
