### ISSUE TITLE
Remove ID

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#33]
@fakhrul-omar

**Comment by fakhrul-omar** [comment]
Which/What ID, DDC ID on the tab? ID column at some (each) object list like AV?

**Comment by mcchai** [comment]
ID column at some (each) object list like AV

**Comment by fakhrul-omar** [comment]
That one I put because it's not like you can depend on object name to know its object ID, especially the one that you can set its name when you create it. Though the default name will be the usual one (i.e. Analog Value 14).

Well then, I'll delete that column.
