### ISSUE TITLE
Change text control validation to not require pressing Enter

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#35]
@fakhrul-omar , it is not user friendly to click enter for each changes made, eg, change timeout

**Comment by fakhrul-omar** [comment]
Ahh, yes it's annoying for user. Plus there're some text entries that requires Enter, some are not. It's just that I don't know when user is actually completed their input entry (especially when validating IP address), thus the Enter key. I can keep validating the entry for each key pressed and change text entry colour accordingly, just thought that it'll pointlessly validating incomplete entry (doesn't actually impact the processor usage though).

**Comment by mcchai** [comment]
We can request the user to press the Enter key. Can we have an indication on when to press the Enter key?

**Comment by fakhrul-omar** [comment]
Ermm...then any text entry that has background colour shall require user to press Enter when they finished typing value in it. Validation is done to check whether value can be converted to floating point, unsigned integer, signed integer or boolean. Or if it's IP address. The one that is simply white, user can put any string in it (like object name when creating new object).

**Comment by kslee911** [comment]
My suggestions:
Single click = Highlight particular text only
Double click = Enable user to change value when applicable
Enter = Update the respective value after double click changes

Do not update the value in the middle of typing.

@fakhrul-omar @mcchai

**Comment by wslow-adft** [comment]
@kslee911 @LOKJK  @thyong-adft  Ready for test

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now. Thank you.
