### ISSUE TITLE
Fixed the width of each column

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#37]
@fakhrul-omar , can we maximize all the width of the tab column so the user does not need to adjust the width so often 

- [x] Autofit column to the content.
- [x] Autofit window to the parent window so that we don't need to scroll down to get to horizontal scroll.

**Comment by fakhrul-omar** [comment]
Tab column means? Column for any table/list? Tab that I currently recognize is DDC tab, BACnet object tab and some variable (AI/AO/BI/BO) tab, so I don't know which tab or what tab column means.

**Comment by mcchai** [comment]
I am referring to all the tab. Can we maximize the tab column so user does not need to adjust the width so often

**Comment by fakhrul-omar** [comment]
![image](https://user-images.githubusercontent.com/29793555/42618601-1c6e398e-85e8-11e8-8f45-500808e6d1c9.png)
These are the ones that I currently recognize as tabs.

**Comment by kslee911** [comment]
Tested ok and closed.
