### ISSUE TITLE
Config Tool performs writeProperty after connect

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#38]
![writeProperty.JPG](https://images.zenhubusercontent.com/5923960351aa2c30577f16b5/c2a914ef-fa5c-4b86-adb6-384efb923d42)

The the values is being written to zero if connected in config tool.

**Comment by kslee911** [comment]
Further found out that the "writeProperty" is performed continuously according to wireshark capture.
@fakhrul-omar

**Comment by wslow-adft** [comment]
@kslee911 @LOKJK  @thyong-adft  Ready

**Comment by kslee911** [comment]
Tested ok at site
