### ISSUE TITLE
Pulse Accumulator at UI should disable user from changing "min pulse" value

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#40]
As understanding from David & Leong, changing this value for UI has no effect. Thus should disable user to change this value. 
![Screenshot (267).png](https://images.zenhubusercontent.com/5923960351aa2c30577f16b5/d6ad0b25-89b0-4ea1-b742-4edb17e33935)

**Comment by wslow-adft** [comment]
@kslee911 @LOKJK  @thyong-adft  Ready for test
