### ISSUE TITLE
Calendar tab still show false response although the condition is met.

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#41]
![calendar](https://user-images.githubusercontent.com/38911466/46568688-c77fc500-c97b-11e8-8630-410824dc8e80.jpg)

**Comment by mcchai** [comment]
@fakhrul-omar

**Comment by wslow-adft** [comment]
maybe not time sysn

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai Ready for test

**Comment by wslow-adft** [comment]
This is because the time in controller is not syns

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now. Thank you.
