### ISSUE TITLE
The calendar data blinks when added the calendar range

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#42]
@fakhrul-omar #
![calendar blink](https://user-images.githubusercontent.com/38911466/46568730-7f14d700-c97c-11e8-8163-5e177e7830ab.jpg)
![calendar blinks](https://user-images.githubusercontent.com/38911466/46568731-7f14d700-c97c-11e8-8499-d19a2d9bfef8.jpg)

**Comment by fakhrul-omar** [comment]
Current explanation is infinite read/write loop after list box detects change event in its value, at which it didn't recognize which one is the actor, user's or its own.

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai Ready for test

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now. Thank you.
