### ISSUE TITLE
The time in the schedule tab cannot be configured

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#44]
@fakhrul-omar 

![cannot edit schedule](https://user-images.githubusercontent.com/38911466/46568750-db77f680-c97c-11e8-9e3d-a9ab0cd3f3c1.jpg)

**Comment by fakhrul-omar** [comment]
Is this not because item in schedule exception is not currently selected while editing item in calendar schedule?

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai  Ready for test. The config tool is not checking whether the calendar have been selected before create the exception time entry. 
A checking process added.

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now. Thank you.
