### ISSUE TITLE
The schedule will have configuration-error status when "Property Reference" is added.

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#45]
@fakhrul-omar 

![schedule will have config error after adding lobinary value](https://user-images.githubusercontent.com/38911466/46568769-44f80500-c97d-11e8-97b3-3b46891b0bc8.jpg)

**Comment by wslow-adft** [comment]
@thyong-adft  @mcchai  ready for test.
- Add a column in schedule list for changing the data type. User will only able to change data type in this column and won't be able to change the data when change the value time entry and schedule default.
- User will only able to select the object type (AO,AV,BV...) according the data type had been selected. (To prevent configuration error cause by selected wrong onject type)

**Comment by mcchai** [comment]
@wslow-adft , I will close the issue now
