### ISSUE TITLE
Config Tool crashed when the logic is compiled without the "variable".

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#46]
@fakhrul-omar 

![compile error](https://user-images.githubusercontent.com/38911466/46568778-622cd380-c97d-11e8-8bec-89145ea40beb.jpg)

**Comment by fakhrul-omar** [comment]
Due to no value block checking (whether it's actually assigned or not) on main statement block (and probably to other blocks too) when actually accessing it when compiling.

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai  Ready for test. It will prompt error message if variable block is not exist.

**Comment by mcchai** [comment]
Noted.  I will close the issue now
