### ISSUE TITLE
IP Logic Min, Max, PI, PID ,Get Value can be compiled but can't export.

### ISSUE THREAD

**Issue by mcchai** [ADFTech/XTEC_X1_Public#47]
@fakhrul-omar 

![bacnet get ao cannot export](https://user-images.githubusercontent.com/38911466/46568848-85a44e00-c97e-11e8-9c14-fdeae6aab14e.jpg)
![bacnet set cannot export](https://user-images.githubusercontent.com/38911466/46568849-863ce480-c97e-11e8-959c-8fd00d6ef19f.jpg)
![pi compilation okay but cant export](https://user-images.githubusercontent.com/38911466/46568850-863ce480-c97e-11e8-927c-186de73dbb69.jpg)
![Uploading PID Compilation okay but cant export.jpg…]()
![Uploading PID Compilation okay but cant export-2.jpg…]()

**Comment by wslow-adft** [comment]
@thyong-adft @mcchai Ready for test.

**Comment by mcchai** [comment]
@wslow-adft , the block can be compiled but it shows Program Error when initiate run program

![logic error](https://user-images.githubusercontent.com/38911466/47254389-62a48e80-d494-11e8-8498-a8f8036411da.jpg)
![logic error2](https://user-images.githubusercontent.com/38911466/47254390-62a48e80-d494-11e8-81a8-3e5f43652d55.jpg)
