### ISSUE TITLE
Unable to search/scan for other device(s) on network after already connected

### ISSUE THREAD

**Issue by fakhrul-omar** [ADFTech/XTEC_X1_Public#5]
After user has connected to device(s), when they try to scan after that, device list will be empty as if there's no device found. This is definitely due to reply from device got received by one of config-tool client(s) and dismissed/dropped as it doesn't match any of currently opened device. So either scan use client as well (and register to message controller) or do as config-tool-v2/yabe do: use another port for receiving device reply.

**Comment by kslee911** [comment]
Tested ok and closed.
