### ISSUE TITLE
Analog Input max/min range does not respond correctly when changed

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#51]

**Comment by fakhrul-omar** [comment]
Steps to reproduce? Perhaps something like:
1. connecting UI to external input.
2. confirming UI value with config-tool-v3 or Yabe is within max/min range.
3. try with smaller range, but UI value doesn't get within range.

**Comment by kslee911** [comment]
Yes, please use config tool v3 to test.

**Comment by david-glover** [comment]
For MSTP devices we have the optional properties:      PROP_MIN_PRES_VALUE, PROP_MAX_PRES_VALUE

These are defined as:
This property, of type REAL, indicates the lowest/highest number in engineering units that can be reliably used for the Present_Value property of this object.

For X1 devices we do not have these properties. 
We do have     PROP_HIGH_LIMIT, PROP_LOW_LIMIT.

These are defined as:
This property is the pHighLimit / pLowLimit parameter for the object's event algorithm. See Clause 13.3 for event algorithm parameter descriptions.

When Config tool sets these values on the X1 device, it fails, property unknown.

**Comment by fakhrul-omar** [comment]
Here it gets more interesting. In config-tool-v3, for setting min/max range value, it first determines whether target device is an IP or MS/TP. If it's MS/TP, it uses PROP\_\*\_PRES_VALUE, and if it's IP, it uses PROP\_\*\_LIMIT. The latter is wrong since, as David described above, those are for event algorithm, not for present value control. Wonder how did I test that property before.

Anyway, the option now is whether David add those optional properties in IP device as well or I remove/hide AI max/min range columns in config-tool-v3.

**Comment by fakhrul-omar** [comment]
Don't know why it says property unknown though, most probably config-tool-v3 detects target device type as MS/TP and uses non-existent PROP_*_PRES_VALUE, which points to another problem...

**Comment by david-glover** [comment]
The first time, it didn't properly detect as X1.  When I was showing
Fakhrul that it didn't detect, it detected properly, and now it writes
low_Limit and High_Limit (which is expected as far as Config Tool is
concerned, but is wrong.)

After discussing with Lee, the Min_Scale and Max_Scale properties are used
and wanted.
It seems that the MSTP device is incorrectly using MIN_PRES_VALUE and
MAX_PRES_VALUE for these values.  Those have a different meaning in
bacnet.  (As the minimum and maximum present value that will give a
reliable reading).

There are functions to set min_scale and max_scale in the X1 device.  Both
are never used.  The values are set to 0 and 100 on initialization.

Second - the Units declared is hard coded as 98 - PERCENT for both units,
even when set to NTC, where it clearly is not returning a PERCENT.  This
should be changed to 95 - UNITS, or possibly depend on the input type.

**Comment by kslee911** [comment]
1. So the correct properties that should be used are min_scale and max_scale for both MSTP and X1? If yes please make the changes to X1 first as I need the scaling to display sensor the reading properly. 

2. We shall proceed to make these unit to NO UNITS (95) as the conditions varies. Setting it to change according to sensor type doesn't fit all conditions. 
Eg. 0-10v sensor type can be PRESSURE, DEG C, DEG F, M3/H etc.

Thanks.

**Comment by kslee911** [comment]
Any updates on this?
@fakhrul-omar @david-glover @thyong-adft @LOKJK

**Comment by thyong-adft** [comment]
@kslee911 they went for 1 day seminar. The issue can be resolved by next week. Let me discuss with them on the exact day.

**Comment by david-glover** [comment]
Scaling as requested has been implemented in XTEC-X1 release v1.1.3-beta.4 with the following properties:
AI_MIN_SCALE (552)
AI_MAX_SCALE (553)

**Comment by fakhrul-omar** [comment]
Done on config-tool side as well. For X1 device that has firmware version below v3.1.1-beta.4, min/max scale columns for analog input in Variables tab will be hidden (user cannot access those).

**Comment by kslee911** [comment]
Thanks @david-glover  @fakhrul-omar 
I will test this by tomorrow.

**Comment by kslee911** [comment]
Tested and functional
