### ISSUE TITLE
Cannot login to webpage after change settings from MSTP Tab

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#52]
Steps:
1. Login to X1 via web
2. Go to MSTP tab, enable/disable either port, then save. Or change other MSTP setting, then save.
3. Go to General Tab, click Reboot.
4. Cannot login to web after that.

It happened to 2 of the X1 devices.

@thyong-adft @LOKJK

**Comment by david-glover** [comment]
Both of the devices had a truncated config file.  (sizes: 86016, 401408.  Should be 1069232).

Tried multiple times to reproduce the error, but did not have any occurrence of the issue.

Need to investigate the save_pending and reboot logic to see what can be changed.
Also will look at implementing a duplicate file backup / alternating write scheme.

**Comment by david-glover** [comment]
fixed in v1.1.3.beta.5.  Added backup config file and prevent saving when SIGTERM triggered by reboot event. 
https://github.com/ADFTech/xtec-uc-ip-main/commit/ea90a9678d0b6fd1174e80872473e6570f2783c0
