### ISSUE TITLE
Device being "Reset" after click Reboot

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#55]
Happened a few times at WHR, HPUPM site after changing Port 1/Port 2 settings through web. 

@thyong-adft @LOKJK

**Comment by fakhrul-omar** [comment]
Reset here means all variables are deleted/returned to default settings, right? This one I guess is due to config.bin got corrupted after reboot, the same thing as #52.

**Comment by thyong-adft** [comment]
Dear all,

Let us discuss on that after release T1 alpha 2.

Regards,
TH Yong
Operations Manager
Mobile: +6016 417 1163

**Comment by david-glover** [comment]
Fix in v.1.1.3.beta.5.  Added backup config, and also prevent saving config from SIGTERM when the reboot was triggered.
https://github.com/ADFTech/xtec-uc-ip-main/commit/ea90a9678d0b6fd1174e80872473e6570f2783c0
