### ISSUE TITLE
AI becomes zero after device running with logic

### ISSUE THREAD

**Issue by kslee911** [ADFTech/XTEC_X1_Public#57]
![AI becomes Zero.jpeg](https://images.zenhubusercontent.com/5923960351aa2c30577f16b5/b2f06669-dfed-4259-bb97-76cbe1ee4127)

I will email the .json file and modbus .csv file.

@thyong-adft @LOKJK

**Comment by fakhrul-omar** [comment]
I heard that @david-glover already worked on this. Current status is?

**Comment by david-glover** [comment]
I believe this is also caused by the program crashing and not saving the config, like other issues.
Likely fixed by https://github.com/ADFTech/xtec-uc-ip-main/commit/ea90a9678d0b6fd1174e80872473e6570f2783c0

**Comment by kslee911** [comment]
Not happening anymore at the moment, should be fixed with recent update.
